export interface MenuItem {
  id: string
  name: string
  description: string
  price: number
  tags: string[]
  seoAlt: string
  spice?: 1 | 2 | 3
  isSignature?: boolean
  proteinOptions?: boolean
  isVegan?: boolean
  isGlutenFree?: boolean
  isOutOfStock?: boolean
  itemNumber?: string
}

export interface MenuCategory {
  id: string
  name: string
  description: string
  items: MenuItem[]
  menuType: 'lunch' | 'all-day'
}

// ─── Lunch Menu ───────────────────────────────────────────────────────────────

export const LUNCH_CATEGORIES: MenuCategory[] = [
  {
    id: 'lunch-soup',
    name: 'Soup',
    description: 'Lunch soup specials',
    menuType: 'lunch',
    items: [
      {
        id: 'l1-wonton-soup',
        itemNumber: 'L1',
        name: 'Wonton Soup',
        description: 'Dumplings filled with chicken and shrimp, spring onion, bean sprouts, spinach and cilantro',
        price: 14,
        tags: ['soup'],
        seoAlt: 'Wonton Soup lunch special at Magnolia Thai Restaurant',
      },
    ],
  },
  {
    id: 'lunch-curry',
    name: 'Curry',
    description: 'Lunch curry specials served with rice',
    menuType: 'lunch',
    items: [
      {
        id: 'l3-red-curry',
        itemNumber: 'L3',
        name: 'Red Curry',
        description: 'Eggplant, bamboo shoots, bell peppers and basil with homemade Thai red curry paste',
        price: 13,
        tags: ['curry', 'coconut'],
        seoAlt: 'Red Curry lunch special at Magnolia Thai Restaurant',
        spice: 2,
        proteinOptions: true,
      },
      {
        id: 'l4-yellow-curry',
        itemNumber: 'L4',
        name: 'Yellow Curry',
        description: 'Thai yellow curry with coconut milk, onions, potatoes, carrots and bell peppers',
        price: 13,
        tags: ['curry', 'coconut'],
        seoAlt: 'Yellow Curry lunch special at Magnolia Thai Restaurant',
        spice: 1,
        proteinOptions: true,
      },
      {
        id: 'l5-panang-curry',
        itemNumber: 'L5',
        name: 'Panang Curry',
        description: 'Thai Panang curry with coconut milk, green beans, bell peppers and shredded kaffir lime leaves',
        price: 13,
        tags: ['curry', 'coconut'],
        seoAlt: 'Panang Curry lunch special at Magnolia Thai Restaurant',
        spice: 2,
        proteinOptions: true,
      },
      {
        id: 'l7-massaman',
        itemNumber: 'L7',
        name: 'Massaman',
        description: 'Potatoes, carrots, onions and peanuts in a rich Thai massaman curry sauce',
        price: 13,
        tags: ['curry', 'coconut', 'mild'],
        seoAlt: 'Massaman Curry lunch special at Magnolia Thai Restaurant',
        spice: 1,
        proteinOptions: true,
      },
    ],
  },
  {
    id: 'lunch-stir-fry',
    name: 'Stir Fry',
    description: 'Lunch stir fry specials served with rice',
    menuType: 'lunch',
    items: [
      {
        id: 'l8-teriyaki',
        itemNumber: 'L8',
        name: 'Teriyaki',
        description: 'Choice of meat with teriyaki sauce, served with steamed vegetables',
        price: 13,
        tags: ['stir-fry'],
        seoAlt: 'Teriyaki lunch special at Magnolia Thai Restaurant',
        proteinOptions: true,
      },
      {
        id: 'l9-sweet-basil',
        itemNumber: 'L9',
        name: 'Sweet Basil',
        description: 'Mushrooms, bell peppers, onions and basil sauteed with special sauce',
        price: 13,
        tags: ['stir-fry'],
        seoAlt: 'Sweet Basil stir fry lunch special at Magnolia Thai Restaurant',
        spice: 2,
        proteinOptions: true,
      },
      {
        id: 'l10-king-rama',
        itemNumber: 'L10',
        name: 'King Rama',
        description: 'Garlic and sauce marinated meat, steamed broccoli, cabbage, carrots, topped with peanut sauce',
        price: 13,
        tags: ['stir-fry', 'peanut'],
        seoAlt: 'King Rama lunch special at Magnolia Thai Restaurant',
        proteinOptions: true,
      },
      {
        id: 'l11-cashew',
        itemNumber: 'L11',
        name: 'Cashew',
        description: 'Choice of meat stir fried with bell pepper, onion, broccoli and cashews with homemade sauce',
        price: 13,
        tags: ['stir-fry'],
        seoAlt: 'Cashew Nut stir fry lunch special at Magnolia Thai Restaurant',
        proteinOptions: true,
      },
      {
        id: 'l12-ginger-lover',
        itemNumber: 'L12',
        name: 'Ginger Lover',
        description: 'Stir fried with fresh ginger, mushrooms, onions and bell peppers',
        price: 13,
        tags: ['stir-fry'],
        seoAlt: 'Ginger Lover stir fry lunch special at Magnolia Thai Restaurant',
        proteinOptions: true,
      },
      {
        id: 'l13-garlic-pepper',
        itemNumber: 'L13',
        name: 'Garlic & Pepper Sauce',
        description: 'Steamed broccoli, cabbage and carrots with fresh garlic and black pepper',
        price: 13,
        tags: ['stir-fry'],
        seoAlt: 'Garlic and Pepper Sauce stir fry lunch special at Magnolia Thai Restaurant',
        proteinOptions: true,
      },
    ],
  },
  {
    id: 'lunch-noodle',
    name: 'Noodle',
    description: 'Lunch noodle specials',
    menuType: 'lunch',
    items: [
      {
        id: 'l14-pad-thai',
        itemNumber: 'L14',
        name: 'Pad Thai',
        description: 'Rice noodles stir fried with egg, green onions, bean sprouts and topped with ground peanuts',
        price: 13,
        tags: ['noodle', 'popular'],
        seoAlt: 'Pad Thai lunch special at Magnolia Thai Restaurant',
        proteinOptions: true,
      },
      {
        id: 'l15-pad-see-ew',
        itemNumber: 'L15',
        name: 'Pad See Ew',
        description: 'Wide rice noodles stir fried with egg, broccoli, carrots and signature sauce',
        price: 13,
        tags: ['noodle'],
        seoAlt: 'Pad See Ew lunch special at Magnolia Thai Restaurant',
        proteinOptions: true,
      },
      {
        id: 'l16-drunken-noodle',
        itemNumber: 'L16',
        name: 'Drunken Noodle',
        description: 'Flat noodles with egg, bell pepper, sweet basil leaf, tomato and onion with bean sprouts',
        price: 13,
        tags: ['noodle', 'spicy'],
        seoAlt: 'Drunken Noodle lunch special at Magnolia Thai Restaurant',
        spice: 2,
        proteinOptions: true,
      },
      {
        id: 'l17-sesame-yakisoba',
        itemNumber: 'L17',
        name: 'Sesame Yakisoba',
        description: 'Fresh Japanese egg noodles with stir fried vegetables, sesame oil and homemade sauce',
        price: 13,
        tags: ['noodle'],
        seoAlt: 'Sesame Yakisoba lunch special at Magnolia Thai Restaurant',
        proteinOptions: true,
      },
    ],
  },
  {
    id: 'lunch-fried-rice',
    name: 'Fried Rice',
    description: 'Lunch fried rice specials',
    menuType: 'lunch',
    items: [
      {
        id: 'l18-pineapple-fried-rice',
        itemNumber: 'L18',
        name: 'Pineapple Fried Rice',
        description: 'Fried rice with egg, cashew nuts, peas-carrots, tomatoes and pineapple',
        price: 13,
        tags: ['rice'],
        seoAlt: 'Pineapple Fried Rice lunch special at Magnolia Thai Restaurant',
        proteinOptions: true,
      },
      {
        id: 'l19-basil-fried-rice',
        itemNumber: 'L19',
        name: 'Basil Fried Rice',
        description: 'Fried rice with bell peppers, onions, tomatoes, topped with cucumber and cilantro',
        price: 13,
        tags: ['rice'],
        seoAlt: 'Basil Fried Rice lunch special at Magnolia Thai Restaurant',
        spice: 2,
        proteinOptions: true,
      },
      {
        id: 'l20-fried-rice',
        itemNumber: 'L20',
        name: 'Fried Rice',
        description: 'Classic Thai fried rice with egg, vegetables and choice of meat',
        price: 13,
        tags: ['rice'],
        seoAlt: 'Thai Fried Rice lunch special at Magnolia Thai Restaurant',
        proteinOptions: true,
      },
    ],
  },
]

// ─── All Day Menu ─────────────────────────────────────────────────────────────

export const ALLDAY_CATEGORIES: MenuCategory[] = [
  {
    id: 'special-menu',
    name: 'Special Menu',
    description: 'Chef signature dishes and house specialties',
    menuType: 'all-day',
    items: [
      {
        id: 's5-duck-curry',
        itemNumber: 'S5',
        name: 'Duck Curry',
        description: 'Roasted duck, tomato, bell pepper, basil, pineapple, broccoli, carrot, pea and carrot in red curry',
        price: 25,
        tags: ['special', 'curry'],
        seoAlt: 'Duck Curry — roasted duck in red curry with pineapple and vegetables at Magnolia Thai Restaurant',
        spice: 2,
        isGlutenFree: true,
        isOutOfStock: true,
        isSignature: true,
      },
      {
        id: 's6-salmon-pumpkin-curry',
        itemNumber: 'S6',
        name: 'Salmon Pumpkin Curry',
        description: 'Grilled wild-caught salmon in special curry sauce with bell pepper, broccoli, bamboo shoots, peas, carrots and basil',
        price: 23,
        tags: ['special', 'seafood', 'curry'],
        seoAlt: 'Salmon Pumpkin Curry — grilled wild-caught salmon in curry sauce at Magnolia Thai Restaurant',
        spice: 2,
        isSignature: true,
      },
      {
        id: 's7-crispy-duck-ginger',
        itemNumber: 'S7',
        name: 'Crispy Duck and Ginger',
        description: 'Deep fried boneless duck topped with mushrooms, carrot, green beans and broccoli. Served with honey-ginger sauce',
        price: 26,
        tags: ['special'],
        seoAlt: 'Crispy Duck and Ginger — deep fried boneless duck with honey-ginger sauce at Magnolia Thai Restaurant',
        isGlutenFree: true,
        isOutOfStock: true,
        isSignature: true,
      },
      {
        id: 's8-peanut-lovers',
        itemNumber: 'S8',
        name: 'Magnolia Thai Peanut Lovers',
        description: 'Thin rice noodles with choice of meat, topped with cabbage, carrot, broccoli and special peanut sauce',
        price: 19,
        tags: ['special', 'peanut', 'noodle'],
        seoAlt: 'Magnolia Thai Peanut Lovers — rice noodles with special peanut sauce at Magnolia Thai Restaurant',
        proteinOptions: true,
      },
      {
        id: 's10-pad-thai-duck',
        itemNumber: 'S10',
        name: 'Pad Thai Duck',
        description: 'Pad Thai noodles, crispy duck, egg, green onions, bean sprouts, ground peanuts',
        price: 20,
        tags: ['special', 'noodle'],
        seoAlt: 'Pad Thai Duck — crispy duck pad thai at Magnolia Thai Restaurant',
        isGlutenFree: true,
        isOutOfStock: true,
      },
      {
        id: 's11-pad-thai-lemongrass',
        itemNumber: 'S11',
        name: 'Pad Thai Lemongrass Chicken',
        description: 'Pad Thai noodles, lemon grass, egg, green onions, bean sprouts, ground peanuts',
        price: 20,
        tags: ['special', 'noodle'],
        seoAlt: 'Pad Thai Lemongrass Chicken at Magnolia Thai Restaurant',
      },
      {
        id: 's13-drunken-yakisoba',
        itemNumber: 'S13',
        name: 'Drunken Yakisoba',
        description: 'Stir-fried noodles in spicy basil chili sauce with shrimp and chicken, egg, onions, bamboo, bell pepper, tomatoes and mushrooms',
        price: 20,
        tags: ['special', 'noodle', 'spicy'],
        seoAlt: 'Drunken Yakisoba — spicy stir-fried noodles with shrimp and chicken at Magnolia Thai Restaurant',
        spice: 3,
      },
      {
        id: 's18-salmon-teriyaki',
        itemNumber: 'S18',
        name: 'Salmon Teriyaki',
        description: 'Grilled salmon with teriyaki sauce, served with cabbage, carrots, and broccoli',
        price: 21,
        tags: ['special', 'seafood'],
        seoAlt: 'Salmon Teriyaki — grilled salmon with teriyaki sauce at Magnolia Thai Restaurant',
        isGlutenFree: true,
      },
      {
        id: 's19-crispy-basil-shrimp-chicken',
        itemNumber: 'S19',
        name: 'Crispy Basil Shrimp & Chicken',
        description: 'Shrimp, chicken, onion, bell pepper, green bean, mushrooms, and basil stir-fried in chili sauce, topped with crispy basil',
        price: 20,
        tags: ['special', 'seafood', 'spicy'],
        seoAlt: 'Crispy Basil Shrimp and Chicken — stir-fried in chili sauce at Magnolia Thai Restaurant',
        spice: 2,
        isGlutenFree: true,
      },
    ],
  },
  {
    id: 'chef-recommend',
    name: 'Chef Recommend',
    description: 'Northern Thai specialties and chef favorites',
    menuType: 'all-day',
    items: [
      {
        id: 'crispy-pork-belly-side',
        itemNumber: 'C5',
        name: 'Crispy Pork Belly (Side)',
        description: 'Crispy pork belly side order',
        price: 9,
        tags: ['chef'],
        seoAlt: 'Crispy Pork Belly side at Magnolia Thai Restaurant',
      },
      {
        id: 'khao-soi-chicken',
        name: 'Khao Soi Chicken',
        description: 'Northern style curry with egg noodles, chicken, shallots, pickled mustard and fried shallots served on top crispy egg noodle',
        price: 18,
        tags: ['chef', 'noodle', 'curry'],
        seoAlt: 'Khao Soi Chicken — Northern Thai curry noodles at Magnolia Thai Restaurant',
        spice: 2,
        isSignature: true,
      },
      {
        id: 'massaman-beef-curry',
        name: 'Massaman Beef Curry',
        description: 'Tender slow-braised beef in rich coconut milk Massaman curry with potatoes, carrots, onions, and peanuts. Mild, creamy, and aromatic',
        price: 17,
        tags: ['chef', 'curry'],
        seoAlt: 'Massaman Beef Curry — slow-braised beef in coconut Massaman curry at Magnolia Thai Restaurant',
        spice: 1,
        isSignature: true,
      },
      {
        id: 'tofu-khao-soi',
        name: 'Tofu Khao Soi',
        description: 'Northern style curry with egg noodles, tofu, shallots, pickled mustard and fried shallots served on top crispy egg noodle',
        price: 17,
        tags: ['chef', 'noodle', 'curry'],
        seoAlt: 'Tofu Khao Soi — vegetarian Northern Thai curry noodles at Magnolia Thai Restaurant',
        spice: 2,
        isVegan: true,
      },
      {
        id: 'tempura-khao-soi',
        name: 'Tempura Khao Soi',
        description: 'Northern style curry with egg noodles, tempura, shallots, pickled mustard and fried shallots served on top crispy egg noodle',
        price: 18,
        tags: ['chef', 'noodle', 'curry'],
        seoAlt: 'Tempura Khao Soi — Northern Thai curry noodles with tempura at Magnolia Thai Restaurant',
        spice: 2,
      },
      {
        id: 'pork-belly-khao-soi',
        name: 'Pork Belly Khao Soi',
        description: 'Northern style curry with egg noodles, pork belly, shallots, pickled mustard and fried shallots served on top crispy egg noodle',
        price: 18,
        tags: ['chef', 'noodle', 'curry'],
        seoAlt: 'Pork Belly Khao Soi — Northern Thai curry noodles with pork belly at Magnolia Thai Restaurant',
        spice: 2,
      },
      {
        id: 'duck-khao-soi',
        name: 'Duck Khao Soi',
        description: 'Northern style curry with egg noodles, duck, shallots, pickled mustard and fried shallots served on top crispy egg noodle',
        price: 20,
        tags: ['chef', 'noodle', 'curry'],
        seoAlt: 'Duck Khao Soi — Northern Thai curry noodles with duck at Magnolia Thai Restaurant',
        spice: 2,
      },
      {
        id: 'salmon-khao-soi',
        name: 'Salmon Khao Soi',
        description: 'Northern style curry with egg noodles, salmon, shallots, pickled mustard and fried shallots served on top crispy egg noodle',
        price: 20,
        tags: ['chef', 'noodle', 'curry', 'seafood'],
        seoAlt: 'Salmon Khao Soi — Northern Thai curry noodles with salmon at Magnolia Thai Restaurant',
        spice: 2,
      },
    ],
  },
  {
    id: 'appetizer',
    name: 'Appetizer',
    description: 'Traditional Thai starters and shareables',
    menuType: 'all-day',
    items: [
      {
        id: 'fried-spring-rolls',
        itemNumber: '1',
        name: 'Fried Spring Rolls (6)',
        description: 'Glass noodles, carrots, cabbage, taro and celery wrapped in rice paper, deep-fried until crispy. Served with sour orange sauce',
        price: 7,
        tags: ['appetizer'],
        seoAlt: 'Fried Spring Rolls at Magnolia Thai Restaurant',
        isVegan: true,
      },
      {
        id: 'fried-tofu',
        itemNumber: '2',
        name: 'Fried Tofu (4)',
        description: 'Fried firm tofu, served with sweet and sour sauce, topped with crushed peanuts',
        price: 6,
        tags: ['appetizer'],
        seoAlt: 'Fried Tofu with peanuts at Magnolia Thai Restaurant',
        isVegan: true,
      },
      {
        id: 'fresh-garden-rolls',
        itemNumber: '3',
        name: 'Fresh Garden Rolls',
        description: 'Mixed vegetable salad with rice vermicelli, choice of meat, served with peanut sauce',
        price: 0,
        tags: ['appetizer', 'fresh'],
        seoAlt: 'Fresh Garden Rolls with peanut sauce at Magnolia Thai Restaurant',
        proteinOptions: true,
      },
      {
        id: 'pot-sticker',
        itemNumber: '4',
        name: 'Pot Sticker',
        description: 'Deep-fried dumplings filled with chicken and vegetables, served with Thai-style ginger soy sauce',
        price: 8,
        tags: ['appetizer'],
        seoAlt: 'Pot Sticker dumplings at Magnolia Thai Restaurant',
      },
      {
        id: 'asian-pumpkin-tempura',
        itemNumber: '5',
        name: 'Asian Pumpkin Tempura (4)',
        description: 'Asian pumpkin tempura breaded with sweet and sour sauce',
        price: 9,
        tags: ['appetizer'],
        seoAlt: 'Asian Pumpkin Tempura at Magnolia Thai Restaurant',
        isVegan: true,
      },
      {
        id: 'chicken-satay',
        itemNumber: '6',
        name: 'Chicken Satay (4)',
        description: 'Grilled chicken marinated in turmeric and coconut milk, served with toast and peanut sauce',
        price: 12,
        tags: ['appetizer', 'popular'],
        seoAlt: 'Chicken Satay with peanut sauce at Magnolia Thai Restaurant',
        isSignature: true,
      },
      {
        id: 'coconut-shrimp',
        itemNumber: '7',
        name: 'Coconut Shrimp (6)',
        description: 'Crispy fried shrimp served with tropical sauce',
        price: 11,
        tags: ['appetizer', 'seafood'],
        seoAlt: 'Coconut Shrimp at Magnolia Thai Restaurant',
      },
      {
        id: 'crab-puffs',
        itemNumber: '8',
        name: 'Crab Puffs (7)',
        description: 'Fried dumplings filled with crab sticks, cream cheese, onions and carrots, served with homemade plum sauce',
        price: 9,
        tags: ['appetizer', 'popular'],
        seoAlt: 'Crab Puffs with plum sauce at Magnolia Thai Restaurant',
      },
      {
        id: 'combo-mixed-appetizer',
        itemNumber: '10',
        name: 'Combo Mixed Appetizer',
        description: 'Egg rolls (2), crab rangoon (3), Chicken Satay (2), Pot Stickers (2)',
        price: 14,
        tags: ['appetizer', 'popular'],
        seoAlt: 'Combo Mixed Appetizer platter at Magnolia Thai Restaurant',
      },
      {
        id: 'shrimp-tempura',
        itemNumber: '12',
        name: 'Shrimp Tempura',
        description: 'Mixed vegetables coated in tempura batter, served with sweet and sour sauce',
        price: 12,
        tags: ['appetizer', 'seafood'],
        seoAlt: 'Shrimp Tempura at Magnolia Thai Restaurant',
      },
      {
        id: 'grilled-pork-skewers',
        itemNumber: '14',
        name: 'Grilled Pork Skewers (Moo Ping)',
        description: 'Grilled pork skewers, served with tamarind sauce, cucumber, tomato, pineapple. Served with sticky rice',
        price: 14,
        tags: ['appetizer'],
        seoAlt: 'Grilled Pork Skewers Moo Ping at Magnolia Thai Restaurant',
        isOutOfStock: true,
      },
    ],
  },
  {
    id: 'salad',
    name: 'Salad',
    description: 'Fresh Thai salads with bold flavors',
    menuType: 'all-day',
    items: [
      {
        id: 'grilled-beef-salad',
        itemNumber: '24',
        name: 'Grilled Beef Salad (Nam-Tok)',
        description: 'Thinly sliced grilled beef tossed with roasted rice powder, fresh herbs, chili, lime juice, and fish sauce',
        price: 17,
        tags: ['salad', 'spicy'],
        seoAlt: 'Grilled Beef Salad Nam-Tok at Magnolia Thai Restaurant',
        spice: 2,
        isGlutenFree: true,
      },
      {
        id: 'chicken-larb',
        itemNumber: '26',
        name: 'Chicken Larb',
        description: 'Traditional Thai minced chicken salad with fresh herbs, lime juice, and roasted rice powder',
        price: 16,
        tags: ['salad', 'spicy'],
        seoAlt: 'Chicken Larb salad at Magnolia Thai Restaurant',
        spice: 2,
        isGlutenFree: true,
      },
      {
        id: 'papaya-salad',
        itemNumber: '21',
        name: 'Papaya Salad (Som-Tum)',
        description: 'Traditional green papaya salad with tomatoes, green beans, peanuts, and spicy lime dressing',
        price: 14,
        tags: ['salad', 'spicy'],
        seoAlt: 'Papaya Salad Som-Tum at Magnolia Thai Restaurant',
        spice: 2,
        isGlutenFree: true,
      },
      {
        id: 'mango-salad',
        itemNumber: '20',
        name: 'Mango Salad with Shrimp & Chicken',
        description: 'Fresh mango salad with shrimp and chicken, tossed in a tangy Thai dressing',
        price: 18,
        tags: ['salad', 'seafood'],
        seoAlt: 'Mango Salad with Shrimp and Chicken at Magnolia Thai Restaurant',
        isGlutenFree: true,
      },
    ],
  },
  {
    id: 'soup',
    name: 'Soup',
    description: 'Aromatic Thai soups with fresh herbs and spices',
    menuType: 'all-day',
    items: [
      {
        id: 'tom-kha',
        itemNumber: '30',
        name: 'Tom Kha',
        description: 'Coconut milk soup with lemongrass, galangal, kaffir lime, onion, coriander, cabbage and mushrooms',
        price: 15,
        tags: ['soup', 'coconut'],
        seoAlt: 'Tom Kha coconut soup at Magnolia Thai Restaurant',
        spice: 1,
        proteinOptions: true,
      },
      {
        id: 'tom-yum',
        itemNumber: '31',
        name: 'Tom Yum',
        description: 'Spicy and sour soup with fresh mushrooms, cabbage, lemongrass, galangal, kaffir lime, tomatoes and lime',
        price: 15,
        tags: ['soup', 'spicy'],
        seoAlt: 'Tom Yum spicy and sour soup at Magnolia Thai Restaurant',
        spice: 3,
        proteinOptions: true,
        isSignature: true,
      },
      {
        id: 'wonton-soup',
        itemNumber: '32',
        name: 'Wonton Soup',
        description: 'Dumplings filled with chicken and shrimp, spring onion, bean sprouts, spinach and cilantro. Add egg noodles for $3',
        price: 15,
        tags: ['soup'],
        seoAlt: 'Wonton Soup at Magnolia Thai Restaurant',
      },
    ],
  },
  {
    id: 'noodle-soup',
    name: 'Noodle Soup',
    description: 'Hearty Thai noodle soups',
    menuType: 'all-day',
    items: [
      {
        id: 'beef-noodles',
        itemNumber: '33',
        name: 'Beef Noodles',
        description: 'Thin rice noodles, bean sprouts, meatballs, green onion, cilantro, celery, darkened broth',
        price: 17,
        tags: ['noodle-soup'],
        seoAlt: 'Beef Noodle Soup at Magnolia Thai Restaurant',
      },
      {
        id: 'khao-soi-noodles',
        itemNumber: '36',
        name: 'Khao Soi Noodles',
        description: 'Northern-style curry dish with egg noodles, chicken, shallots, pickled mustard greens and fried shallots. Served on crispy egg noodles',
        price: 18,
        tags: ['noodle-soup', 'curry'],
        seoAlt: 'Khao Soi Noodle Soup — Northern Thai curry noodles at Magnolia Thai Restaurant',
        spice: 2,
        isSignature: true,
      },
      {
        id: 'chicken-noodle-soup',
        itemNumber: '37',
        name: 'Chicken Noodle Soup',
        description: 'Classic Thai chicken noodle soup with fresh herbs',
        price: 15,
        tags: ['noodle-soup'],
        seoAlt: 'Chicken Noodle Soup at Magnolia Thai Restaurant',
      },
    ],
  },
  {
    id: 'grilled',
    name: 'Grilled',
    description: 'Grilled specialties with fresh accompaniments',
    menuType: 'all-day',
    items: [
      {
        id: 'honey-lemongrass-chicken',
        itemNumber: 'G1',
        name: 'Honey Lemongrass Chicken',
        description: 'Grilled lemongrass chicken with rice vermicelli, mixed vegetables, Vietnamese pickles, cucumber, coriander, crushed peanuts, bean sprouts, served with Vietnamese special fish sauce and spring rolls',
        price: 18,
        tags: ['grilled'],
        seoAlt: 'Honey Lemongrass Chicken with vermicelli at Magnolia Thai Restaurant',
        isGlutenFree: true,
      },
      {
        id: 'lemongrass-chicken',
        itemNumber: 'G2',
        name: 'Lemongrass Chicken',
        description: 'Grilled lemongrass marinated chicken served with fresh accompaniments',
        price: 18,
        tags: ['grilled'],
        seoAlt: 'Lemongrass Chicken at Magnolia Thai Restaurant',
        isGlutenFree: true,
      },
    ],
  },
  {
    id: 'stir-fry',
    name: 'Stir Fry',
    description: 'Wok-fired dishes served with jasmine rice',
    menuType: 'all-day',
    items: [
      {
        id: 'king-rama',
        itemNumber: '38',
        name: 'King Rama',
        description: 'Garlic and sauce marinated meat, steamed broccoli, cabbage, carrots, topped with peanut sauce',
        price: 15,
        tags: ['stir-fry', 'peanut'],
        seoAlt: 'King Rama with peanut sauce at Magnolia Thai Restaurant',
        proteinOptions: true,
      },
      {
        id: 'cashew-nut',
        itemNumber: '39',
        name: 'Cashew Nut',
        description: 'Choice of meat stir fried with bell pepper, onion, broccoli and cashews topped with homemade sauce',
        price: 15,
        tags: ['stir-fry'],
        seoAlt: 'Cashew Nut stir fry at Magnolia Thai Restaurant',
        proteinOptions: true,
      },
      {
        id: 'sweet-eggplant',
        itemNumber: '40',
        name: 'Sweet Eggplant',
        description: 'Stir fried eggplant with choice of meat in sweet basil sauce',
        price: 15,
        tags: ['stir-fry'],
        seoAlt: 'Sweet Eggplant stir fry at Magnolia Thai Restaurant',
        proteinOptions: true,
      },
      {
        id: 'garlic-black-pepper',
        itemNumber: '41',
        name: 'Garlic & Black Pepper Sauce',
        description: 'Steamed broccoli, cabbage and carrots with choice of meat, fresh garlic and black pepper',
        price: 15,
        tags: ['stir-fry'],
        seoAlt: 'Garlic and Black Pepper Sauce stir fry at Magnolia Thai Restaurant',
        proteinOptions: true,
      },
      {
        id: 'sweet-basil',
        itemNumber: '42',
        name: 'Sweet Basil (Pad Kra Pao)',
        description: 'Mushrooms, bell peppers, onions and basil, sauteed with special sauce and choice of meat',
        price: 15,
        tags: ['stir-fry', 'spicy'],
        seoAlt: 'Sweet Basil Pad Kra Pao stir fry at Magnolia Thai Restaurant',
        spice: 2,
        proteinOptions: true,
      },
      {
        id: 'pad-prik-khing',
        itemNumber: '43',
        name: 'Pad Prik-Khing',
        description: 'Choice of meat with sweet green beans, red bell peppers and kaffir lime leaves with Thai chili paste',
        price: 15,
        tags: ['stir-fry', 'spicy'],
        seoAlt: 'Pad Prik-Khing stir fry at Magnolia Thai Restaurant',
        spice: 2,
        proteinOptions: true,
      },
    ],
  },
  {
    id: 'noodles',
    name: 'Noodles',
    description: 'Classic Thai noodle dishes',
    menuType: 'all-day',
    items: [
      {
        id: 'pad-thai',
        itemNumber: '44',
        name: 'Pad Thai',
        description: 'Rice noodles stir fried with egg, green onions, bean sprouts and topped with ground peanuts',
        price: 15,
        tags: ['noodle', 'popular'],
        seoAlt: 'Pad Thai — classic Thai stir-fried rice noodles at Magnolia Thai Restaurant',
        proteinOptions: true,
        isSignature: true,
      },
      {
        id: 'pad-see-ew',
        itemNumber: '45',
        name: 'Pad See Ew',
        description: 'Wide rice noodles stir fried with egg, broccoli, carrots and signature sauce',
        price: 15,
        tags: ['noodle'],
        seoAlt: 'Pad See Ew — wide rice noodles at Magnolia Thai Restaurant',
        proteinOptions: true,
      },
      {
        id: 'pad-drunken-noodles',
        itemNumber: '46',
        name: 'Pad Drunken Noodles',
        description: 'Flat noodles with egg, bell pepper, sweet basil leaf, tomato and onion. Served with fresh bean sprouts',
        price: 15,
        tags: ['noodle', 'spicy'],
        seoAlt: 'Drunken Noodles — spicy flat noodles with basil at Magnolia Thai Restaurant',
        spice: 2,
        proteinOptions: true,
      },
      {
        id: 'sesame-yakisoba',
        itemNumber: '47',
        name: 'Sesame Yakisoba',
        description: 'Fresh Japanese egg noodles with stir fried cabbage, carrots, broccoli, onion, sprouts, green onions, sesame oil, homemade sauce',
        price: 15,
        tags: ['noodle'],
        seoAlt: 'Sesame Yakisoba noodles at Magnolia Thai Restaurant',
        proteinOptions: true,
      },
      {
        id: 'glass-noodles-pad-thai',
        name: 'Glass Noodles Pad Thai',
        description: 'Pad Thai made with glass noodles, egg, green onions, bean sprouts and ground peanuts',
        price: 15,
        tags: ['noodle'],
        seoAlt: 'Glass Noodles Pad Thai at Magnolia Thai Restaurant',
        proteinOptions: true,
        isGlutenFree: true,
      },
    ],
  },
  {
    id: 'curry',
    name: 'Curry',
    description: 'Traditional Thai curries with coconut milk — served with jasmine rice',
    menuType: 'all-day',
    items: [
      {
        id: 'red-curry',
        itemNumber: '48',
        name: 'Red Curry',
        description: 'Eggplant, bamboo shoots, bell peppers and basil with homemade Thai red curry paste and choice of protein',
        price: 15,
        tags: ['curry', 'coconut'],
        seoAlt: 'Thai Red Curry at Magnolia Thai Restaurant',
        spice: 2,
        proteinOptions: true,
      },
      {
        id: 'yellow-curry',
        itemNumber: '49',
        name: 'Yellow Curry',
        description: 'Thai yellow curry with coconut milk, onions, potatoes, carrots, bell peppers and choice of protein',
        price: 15,
        tags: ['curry', 'coconut'],
        seoAlt: 'Thai Yellow Curry at Magnolia Thai Restaurant',
        spice: 1,
        proteinOptions: true,
      },
      {
        id: 'pumpkin-curry',
        itemNumber: '50',
        name: 'Pumpkin Curry',
        description: 'Pumpkin with red curry paste, carrots, bell peppers, peas and basil',
        price: 18,
        tags: ['curry', 'coconut'],
        seoAlt: 'Pumpkin Curry at Magnolia Thai Restaurant',
        spice: 2,
        proteinOptions: true,
      },
      {
        id: 'massaman',
        itemNumber: '51',
        name: 'Massaman',
        description: 'Potatoes, carrots, onions and peanuts in a rich Thai massaman curry sauce',
        price: 15,
        tags: ['curry', 'coconut', 'mild'],
        seoAlt: 'Massaman Curry at Magnolia Thai Restaurant',
        spice: 1,
        proteinOptions: true,
        isSignature: true,
      },
      {
        id: 'mango-curry',
        itemNumber: '52',
        name: 'Mango Curry',
        description: 'Yellow curry paste in coconut milk, mixed with fresh mango, onion, broccoli, carrot and bell pepper',
        price: 16,
        tags: ['curry', 'coconut'],
        seoAlt: 'Mango Curry at Magnolia Thai Restaurant',
        spice: 1,
        proteinOptions: true,
      },
      {
        id: 'panang-curry',
        itemNumber: '53',
        name: 'Panang Curry',
        description: 'Thai Panang Curry with coconut milk, green beans, bell peppers and shredded kaffir lime leaves',
        price: 15,
        tags: ['curry', 'coconut'],
        seoAlt: 'Panang Curry at Magnolia Thai Restaurant',
        spice: 2,
        proteinOptions: true,
      },
    ],
  },
  {
    id: 'fried-rice',
    name: 'Fried Rice',
    description: 'Wok-fried jasmine rice dishes',
    menuType: 'all-day',
    items: [
      {
        id: 'pineapple-fried-rice',
        itemNumber: '54',
        name: 'Pineapple Fried Rice',
        description: 'Fried rice with choice of meat, egg, cashew nuts, peas-carrots, tomatoes and pineapple, topped with cucumber and cilantro',
        price: 15,
        tags: ['rice'],
        seoAlt: 'Pineapple Fried Rice at Magnolia Thai Restaurant',
        proteinOptions: true,
      },
      {
        id: 'fried-rice',
        itemNumber: '55',
        name: 'Fried Rice',
        description: 'Classic Thai fried rice with egg, vegetables and choice of meat',
        price: 15,
        tags: ['rice'],
        seoAlt: 'Thai Fried Rice at Magnolia Thai Restaurant',
        proteinOptions: true,
      },
      {
        id: 'basil-fried-rice',
        itemNumber: '57',
        name: 'Basil Fried Rice',
        description: 'Fried rice with choice of meat, bell peppers, onions, tomatoes, topped with cucumber and cilantro',
        price: 15,
        tags: ['rice', 'spicy'],
        seoAlt: 'Basil Fried Rice at Magnolia Thai Restaurant',
        spice: 2,
        proteinOptions: true,
      },
      {
        id: 'duck-fried-rice',
        itemNumber: '58',
        name: 'Duck Fried Rice',
        description: 'Fried rice with duck, eggs, onions, peas, carrots and green onion',
        price: 23,
        tags: ['rice'],
        seoAlt: 'Duck Fried Rice at Magnolia Thai Restaurant',
        isOutOfStock: true,
      },
    ],
  },
  {
    id: 'side-order',
    name: 'Side Order',
    description: 'Rice, noodles, and accompaniments',
    menuType: 'all-day',
    items: [
      {
        id: 'jasmine-rice-s',
        name: 'Jasmine Rice (S)',
        description: 'Steamed jasmine rice — small',
        price: 3,
        tags: ['side'],
        seoAlt: 'Small Jasmine Rice at Magnolia Thai Restaurant',
        isVegan: true,
        isGlutenFree: true,
      },
      {
        id: 'jasmine-rice-l',
        name: 'Jasmine Rice (L)',
        description: 'Steamed jasmine rice — large',
        price: 5,
        tags: ['side'],
        seoAlt: 'Large Jasmine Rice at Magnolia Thai Restaurant',
        isVegan: true,
        isGlutenFree: true,
      },
      {
        id: 'brown-rice',
        name: 'Brown Rice',
        description: 'Steamed brown rice',
        price: 4,
        tags: ['side'],
        seoAlt: 'Brown Rice at Magnolia Thai Restaurant',
        isVegan: true,
        isGlutenFree: true,
      },
      {
        id: 'sticky-rice',
        name: 'Sticky Rice',
        description: 'Traditional Thai sticky rice',
        price: 3,
        tags: ['side'],
        seoAlt: 'Sticky Rice at Magnolia Thai Restaurant',
        isVegan: true,
        isGlutenFree: true,
      },
      {
        id: 'peanut-sauce-s',
        name: 'Peanut Sauce (S)',
        description: 'House peanut sauce — small',
        price: 3,
        tags: ['side'],
        seoAlt: 'Small Peanut Sauce at Magnolia Thai Restaurant',
        isVegan: true,
      },
      {
        id: 'peanut-sauce-l',
        name: 'Peanut Sauce (L)',
        description: 'House peanut sauce — large',
        price: 5,
        tags: ['side'],
        seoAlt: 'Large Peanut Sauce at Magnolia Thai Restaurant',
        isVegan: true,
      },
      {
        id: 'steamed-noodles',
        name: 'Steamed Noodles',
        description: 'Steamed noodles',
        price: 4,
        tags: ['side'],
        seoAlt: 'Steamed Noodles at Magnolia Thai Restaurant',
        isVegan: true,
      },
      {
        id: 'steamed-veggies',
        name: 'Steamed Veggies (Organic)',
        description: 'Steamed organic vegetables',
        price: 4,
        tags: ['side'],
        seoAlt: 'Steamed Organic Vegetables at Magnolia Thai Restaurant',
        isVegan: true,
        isGlutenFree: true,
      },
    ],
  },
  {
    id: 'dessert',
    name: 'Dessert',
    description: 'Traditional Thai sweets',
    menuType: 'all-day',
    items: [
      {
        id: 'mango-sticky-rice',
        name: 'Mango Sticky Rice',
        description: 'Sweet sticky rice with fresh mango and warm coconut cream',
        price: 10,
        tags: ['dessert', 'popular'],
        seoAlt: 'Mango Sticky Rice dessert at Magnolia Thai Restaurant',
        isSignature: true,
        isGlutenFree: true,
      },
      {
        id: 'chocolate-lava-cake',
        name: 'Chocolate Lava Cake',
        description: 'Warm chocolate lava cake with a molten center',
        price: 7,
        tags: ['dessert'],
        seoAlt: 'Chocolate Lava Cake at Magnolia Thai Restaurant',
      },
    ],
  },
  {
    id: 'beverages',
    name: 'Beverages',
    description: 'Thai teas, fresh juices, and soft drinks',
    menuType: 'all-day',
    items: [
      {
        id: 'thai-iced-tea',
        name: 'Thai Iced Tea',
        description: 'Classic Thai iced tea with cream',
        price: 6,
        tags: ['beverage', 'popular'],
        seoAlt: 'Thai Iced Tea at Magnolia Thai Restaurant',
        isSignature: true,
      },
      {
        id: 'thai-iced-coffee',
        name: 'Thai Iced Coffee',
        description: 'Traditional Thai iced coffee with cream',
        price: 6,
        tags: ['beverage'],
        seoAlt: 'Thai Iced Coffee at Magnolia Thai Restaurant',
      },
      {
        id: 'japanese-sencha-tea',
        name: 'Japanese Sencha Tea',
        description: 'Hot Japanese Sencha green tea',
        price: 4,
        tags: ['beverage', 'hot'],
        seoAlt: 'Japanese Sencha Tea at Magnolia Thai Restaurant',
      },
      {
        id: 'jasmine-tea',
        name: 'Jasmine Tea',
        description: 'Hot jasmine tea',
        price: 4,
        tags: ['beverage', 'hot'],
        seoAlt: 'Jasmine Tea at Magnolia Thai Restaurant',
      },
      {
        id: 'ginger-lemon-tea',
        name: 'Ginger Lemon Tea',
        description: 'Hot ginger lemon tea',
        price: 4,
        tags: ['beverage', 'hot'],
        seoAlt: 'Ginger Lemon Tea at Magnolia Thai Restaurant',
      },
      {
        id: 'green-tea',
        name: 'Green Tea',
        description: 'Hot green tea',
        price: 4,
        tags: ['beverage', 'hot'],
        seoAlt: 'Green Tea at Magnolia Thai Restaurant',
      },
      {
        id: 'mango-juice',
        name: 'Mango Juice',
        description: 'Fresh mango juice',
        price: 4,
        tags: ['beverage'],
        seoAlt: 'Mango Juice at Magnolia Thai Restaurant',
      },
      {
        id: 'strawberry-lemonade',
        name: 'Strawberry Lemonade',
        description: 'Fresh strawberry lemonade',
        price: 4,
        tags: ['beverage'],
        seoAlt: 'Strawberry Lemonade at Magnolia Thai Restaurant',
      },
      {
        id: 'diet-coke',
        name: 'Diet Coke',
        description: 'Diet Coke',
        price: 3,
        tags: ['beverage', 'soda'],
        seoAlt: 'Diet Coke at Magnolia Thai Restaurant',
      },
      {
        id: 'sprite',
        name: 'Sprite',
        description: 'Sprite',
        price: 3,
        tags: ['beverage', 'soda'],
        seoAlt: 'Sprite at Magnolia Thai Restaurant',
      },
      {
        id: 'lemonade',
        name: 'Lemonade',
        description: 'Fresh lemonade',
        price: 3,
        tags: ['beverage'],
        seoAlt: 'Lemonade at Magnolia Thai Restaurant',
      },
      {
        id: 'coke',
        name: 'Coke',
        description: 'Coca-Cola',
        price: 3,
        tags: ['beverage', 'soda'],
        seoAlt: 'Coca-Cola at Magnolia Thai Restaurant',
      },
      {
        id: 'pepsi',
        name: 'Pepsi',
        description: 'Pepsi',
        price: 3,
        tags: ['beverage', 'soda'],
        seoAlt: 'Pepsi at Magnolia Thai Restaurant',
      },
      {
        id: 'spring-water',
        name: 'Spring Water',
        description: 'Bottled spring water',
        price: 2,
        tags: ['beverage'],
        seoAlt: 'Spring Water at Magnolia Thai Restaurant',
      },
    ],
  },
  {
    id: 'beer',
    name: 'Beer',
    description: 'Asian imports and local craft beers',
    menuType: 'all-day',
    items: [
      {
        id: 'singha',
        name: 'Singha',
        description: 'Thai lager',
        price: 6,
        tags: ['beer', 'import'],
        seoAlt: 'Singha Thai Beer at Magnolia Thai Restaurant',
      },
      {
        id: 'chang',
        name: 'Chang',
        description: 'Thai lager',
        price: 6,
        tags: ['beer', 'import'],
        seoAlt: 'Chang Thai Beer at Magnolia Thai Restaurant',
      },
      {
        id: 'tsing-tao',
        name: 'Tsing Tao',
        description: 'Chinese lager',
        price: 6,
        tags: ['beer', 'import'],
        seoAlt: 'Tsing Tao Beer at Magnolia Thai Restaurant',
      },
      {
        id: 'beer-lao',
        name: 'Beer Lao',
        description: 'Laotian lager',
        price: 6,
        tags: ['beer', 'import'],
        seoAlt: 'Beer Lao at Magnolia Thai Restaurant',
      },
      {
        id: 'sapporo',
        name: 'Sapporo',
        description: 'Japanese lager',
        price: 6,
        tags: ['beer', 'import'],
        seoAlt: 'Sapporo Beer at Magnolia Thai Restaurant',
      },
      {
        id: 'ninkasi-ipa',
        name: 'Ninkasi IPA',
        description: 'Local craft IPA',
        price: 6,
        tags: ['beer', 'craft'],
        seoAlt: 'Ninkasi IPA at Magnolia Thai Restaurant',
      },
      {
        id: 'modelo',
        name: 'Modelo',
        description: 'Mexican lager',
        price: 5,
        tags: ['beer', 'import'],
        seoAlt: 'Modelo at Magnolia Thai Restaurant',
      },
      {
        id: 'widmer-hefeweizen',
        name: 'Widmer Hefeweizen',
        description: 'Local wheat beer',
        price: 5,
        tags: ['beer', 'craft'],
        seoAlt: 'Widmer Hefeweizen at Magnolia Thai Restaurant',
      },
      {
        id: 'portland-cider',
        name: 'Portland Cider',
        description: 'Local craft cider',
        price: 5,
        tags: ['beer', 'craft'],
        seoAlt: 'Portland Cider at Magnolia Thai Restaurant',
        isGlutenFree: true,
      },
      {
        id: 'voodoo-ipa',
        name: 'Voodoo IPA',
        description: 'Local craft IPA',
        price: 6,
        tags: ['beer', 'craft'],
        seoAlt: 'Voodoo IPA at Magnolia Thai Restaurant',
      },
    ],
  },
  {
    id: 'wine',
    name: 'Wine',
    description: 'House wines and varietals',
    menuType: 'all-day',
    items: [
      {
        id: 'house-white-wine',
        name: 'House White Wine',
        description: 'House white wine',
        price: 6,
        tags: ['wine'],
        seoAlt: 'House White Wine at Magnolia Thai Restaurant',
        isGlutenFree: true,
      },
      {
        id: 'house-red-wine',
        name: 'House Red Wine',
        description: 'House red wine',
        price: 6,
        tags: ['wine'],
        seoAlt: 'House Red Wine at Magnolia Thai Restaurant',
        isGlutenFree: true,
      },
      {
        id: 'chardonnay',
        name: 'Chardonnay',
        description: 'Chardonnay',
        price: 7,
        tags: ['wine', 'white'],
        seoAlt: 'Chardonnay at Magnolia Thai Restaurant',
        isGlutenFree: true,
      },
      {
        id: 'cabernet',
        name: 'Cabernet',
        description: 'Cabernet Sauvignon',
        price: 7,
        tags: ['wine', 'red'],
        seoAlt: 'Cabernet Sauvignon at Magnolia Thai Restaurant',
        isGlutenFree: true,
      },
      {
        id: 'pinot-noir',
        name: 'Pinot Noir',
        description: 'Pinot Noir',
        price: 7,
        tags: ['wine', 'red'],
        seoAlt: 'Pinot Noir at Magnolia Thai Restaurant',
        isGlutenFree: true,
      },
      {
        id: 'pinot-grigio',
        name: 'Pinot Grigio',
        description: 'Pinot Grigio',
        price: 7,
        tags: ['wine', 'white'],
        seoAlt: 'Pinot Grigio at Magnolia Thai Restaurant',
        isGlutenFree: true,
      },
    ],
  },
]

// ─── Combined export ──────────────────────────────────────────────────────────

export const MENU_CATEGORIES: MenuCategory[] = [...LUNCH_CATEGORIES, ...ALLDAY_CATEGORIES]

export const PROTEIN_OPTIONS = ['Chicken', 'Beef', 'Pork', 'Tofu (V)', 'Shrimp (+$2)', 'Prawns (+$2)']
